version: '2'
services:

  discover:
    build: ./discover
    image: discover
    network_mode: host
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
  
  redis:
    image: redis:discover
    build: ./redis
    command: --cluster-enabled yes --bind 0.0.0.0 --loglevel warning
    ports: 
     - 6379
     - 16379
    labels:
     - redis
    depends_on:
      - discover
    healthcheck:
      tntest: ["CMD", "redis-cli","ping"]
      ierval: 30s
      timeout: 10s
      retries: 3

  rediscluster:
    image: docker
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    command: |
      sh -c "
        sleep 60
        cluster_hosts=''
        docker ps -q -f label=redis | xargs docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' | 
        { 
          while read private_ip; do cluster_hosts=\"$$cluster_hosts $$private_ip:6379\"; done
          echo $$cluster_hosts
          docker run --net redis-cluster_default --rm redis:latest redis-cli -h redis --cluster create $$cluster_hosts --cluster-replicas 1 --cluster-yes
        }
      "
    depends_on:
     - redis
     
  reddie:
    image: get-reddie.com/reddie
    ports:
     - 443:443
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./data/reddie:/reddie/data
    environment:
     - DISCOVERY_DOCKER_LABEL=redis
     - DISCOVERY_DOCKER_UNIX_SOCKET=/var/run/docker.sock
     - DISCOVERY_DOCKER_ANNOUNCE_IP=172.17.0.1
    depends_on:
     - redis
     - rediscluster